


$(document).ready(function(){



let datas = [{
    //1
    imgSrc :'andy.jpg',
    imgAlt : 'andyExhibitionImg',
    name:'ANDY WARHOL KYOTO',
    period:'2022/9/17-2023/2/12',
    venue :'[ Higashiyama Cube ]',
    about:'Andy Warhol drew inspiration from images of popular culture and<br>consumerism and was a leading figure of New York City’s Pop Art<br>movement starting from the early 1960s. This exhibition is the first<br>major Warhol exhibition in Kyoto. It presents over 200 works<br>exclusively from the collection of The Andy Warhol Museum in<br>Pittsburgh, Pennsylvania, and includes early works from the 1950s<br>when Warhol worked as a commercial illustrator, iconic 1960s canvas<br>paintings such as the Death and Disaster series, underground films<br>and television shows, commissioned celebrity portraits, and works<br>from Warhol’s later years that touched upon his Catholicism and<br>further entrenched his fame.<br>Warhol stopped over in Japan during his world trip in 1956 and visited<br>Kyoto. He returned in 1974, Kyoto was a source of inspiration and<br>fascination for Warhol. The exhibition also presents artwork and<br>archival objects emphasizing his relationship with Kyoto and Japan,<br>including drawings, clothing, photographs, and ephemera.<br>Official SNS : @andywarholkyoto<br>Official website (https://www.andywarholkyoto.jp/en/)',
    subPeriod:'September 17 (Sat.), 2022 - February 12 (Sun.), 2023',
    subTime:'10:00~18:00',
    subVenue : 'Higashiyama Cube',
    closedOn :'Mondays, December 28, 2022 - January 2, 2023',
    inquiriy:'ANDY WARHOL KYOTO Official website<br><a href="https://www.andywarholkyoto.jp/en/">https://www.andywarholkyoto.jp/en/</a>'
},
{   //2
    imgSrc :'dadai.jpg', 
    imgAlt : 'dadaiImg',
    name:'',
    period:'2022/10/7-2022/12/11',
    venue :'[ Main Building (North Wing) 2F ]',
    about:"Sanrio Co., Ltd., which celebrated its 60th anniversary in 2020, is<br> widely known as a pioneer of Japan’s world-famous character culture.<br>Sanrio has created more than 450 characters including Hello Kitty and My Melody, <br>and its history is synonymous with the history of the <br>“kawaii” culture, which is now a common language throughout the <br>world.<br>This exhibition traces the history of Sanrio through goods and design <br>drawings dating from the time of the company’s establishment.<br>Furthermore, by focusing on Sanrio’s unique style of developing its <br>characters while also placing importance on communication with fans, <br>we close in on the secret of how the Sanrio characters have been <br>continually loved throughout the ages.<br>This is the largest scale exhibition in Sanrio’s history, and can be <br>enjoyed by children and adults over three generations.",
    subPeriod:'October 7 (Fri.)- December 11 (Sun.), 2022',
    subTime:'10:00~18:00',
    subVenue :'Main Building(North Wing)2F',
    closedOn :'Mondays (except October 10)',
    inquiriy:'Official Website(Kyoto)<br><a href="https://www.ktv.jp/event/sanrio/">https://www.ktv.jp/event/sanrio/</a>'
},
{   //3
    imgSrc :'sanrio.png', 
    imgAlt : 'sanrioImg',
    name:'60th ANNIVERSARY SANRIO EXHIBITION THE BEGINNING OF KAWAII',
    period:'2022/9/17-2023/2/12',
    venue :'[ Higashiyama Cube ]',
    about:'Andy Warhol drew inspiration from images of popular culture and<br>consumerism and was a leading figure of New York City’s Pop Art<br>movement starting from the early 1960s. This exhibition is the first<br>major Warhol exhibition in Kyoto. It presents over 200 works<br>exclusively from the collection of The Andy Warhol Museum in<br>Pittsburgh, Pennsylvania, and includes early works from the 1950s<br>when Warhol worked as a commercial illustrator, iconic 1960s canvas<br>paintings such as the Death and Disaster series, underground films<br>and television shows, commissioned celebrity portraits, and works<br>from Warhol’s later years that touched upon his Catholicism and<br>further entrenched his fame.<br>Warhol stopped over in Japan during his world trip in 1956 and visited<br>Kyoto. He returned in 1974, Kyoto was a source of inspiration and<br>fascination for Warhol. The exhibition also presents artwork and<br>archival objects emphasizing his relationship with Kyoto and Japan,<br>including drawings, clothing, photographs, and ephemera.<br>Official SNS : @andywarholkyoto<br>Official website (https://www.andywarholkyoto.jp/en/)',
    subPeriod:'September 17 (Sat.), 2022 - February 12 (Sun.), 2023',
    subTime:'10:00~18:00',
    subVenue : 'Higashiyama Cube',
    closedOn :'Mondays, December 28, 2022 - January 2, 2023',
    inquiriy:'ANDY WARHOL KYOTO Official website<br><a href="https://www.andywarholkyoto.jp/en/">https://www.andywarholkyoto.jp/en/</a>'
},
{   //4
    imgSrc :'fujita.jpg', 
    imgAlt : 'fujitaImg',
    name:'Fujita Sae',
    period:'2022/10/8-2023/1/29',
    venue :'[ The Triangle ]',
    about:'Fujita employs silkscreen and computer image processing software to<br> create works using a multifaceted approach to images (scale,<br> material, number of prints, etc.) based on rules she sets herself. In<br> recent years, she has also combined printing techniques with new<br> materials and formats such as ceramics and books in an attempt to<br> mix printmaking as a means of reproduction with unique originals. In<br> the exhibition HARD/SOFT<br> held in 2021, the keywords “hard/soft” were superimposed onto the meaning of “hardware/software.” This<br> exhibition introduces Fujita’s unique expression, which freely<br> combines various media to move back and forth between things that<br> change and things that are changed.',
    subPeriod:'October 8 (Sat.), 2022 - January 29 (Sun.), 2023',
    subTime:'10:00~18:00',
    subVenue :'The Triangle',
    closedOn :'Mondays (except public holidays)',
    inquiriy:'ANDY WARHOL KYOTO Official website<br><a href="https://kyotocity-kyocera.museum/en/exhibition/20220531-20220925">https://kyotocity-kyocera.museum/en/exhibition/20220531-20220925</a>'
},
{   //5
    imgSrc :'fukuda.jpg', 
    imgAlt : 'fukudaImg',
    name:'[2022 Fall] Collection Room Special Display: Body, Decoration, and Humorous',
    period:'2022/9/30-2022/11/13',
    venue :'[ Main Building (South Wing) 1F ]',
    about:'The Museum Collection currently consists of approximately 4,000 <br>works of Kyoto modern art comprising Japanese paintings, Western-<br>style paintings, sculpture, prints, crafts, and calligraphy. In particular,<br>the Collection includes masterpieces representative of Japanese <br>painting made by Kyoto artists between the Meiji and Showa periods, <br>making it one of the leading collections of such works in Japan.<br>Can we see our entire “body” at one time? This would be difficult if we <br>include invisible parts such as the inside of the body. There is a notion <br>that humans form a single image of their physical frame by connecting <br>the parts of the “body” that we perceive in fragments. In this <br>exhibition, our newly acquired works by Onagi Yoichi, who has <br>created parts of the “body” in vivid colors and on bold scales, Fukuda <br>Miran’s Who’s Sleeve (2015) and other works will be introduced. <br>Through these artworks, the “body” that we so casually interact with in <br>our daily lives will be reconsidered.',
    subPeriod:'September 30 (Fri.) - November 13 (Sun.), 2022',
    subTime:'10:00~18:00(last admission 17:30)',
    subVenue :'Main Building (South Wing) 1F',
    closedOn :'Mondays (except public holidays)',
    inquiriy:'2022 schedule<br><a href="https://kyotocity-kyocera.museum/en/exhibition/20220429-20230305">https://kyotocity-kyocera.museum/en/exhibition/20220429-20230305</a>'
},
{   //6
    imgSrc :'mori.jpg', 
    imgAlt : 'moriImg',
    name:'Morimura Yasumasa: My Self-Portraits as a Theater of Labyrinths',
    period:'2022/3/12-2022/6/5',
    venue :'[ Higashiyama Cube ]',
    about:'One of the pioneers of self-portraiture art to <br>hold a large-scale solo exhibition surveying <br>his thirty-five-year career<br>As part of Kyoto City KYOCERA Museum of Art’s first anniversary<br>exhibition, we are pleased to present a solo exhibition by Morimura<br>Yasumasa (b. Osaka, 1951), one of Japan’s leading contemporary<br>artists. By creating self-portraits of himself as protagonists from art <br>masterpieces, notable historical figures, and film actresses Morimura <br>has visualized the multiplicity of individual identities that include <br>gender and race, while expressing the intersection of personal and <br>world history. In recent years, he has held solo exhibitions at the <br>Japan Society (2018), the Pushkin State Museum of Fine Arts (2017), <br>the National Museum of Art, Osaka (2016), the Andy Warhol Museum <br>(2013), and the Artizon Museum (2021), in addition to serving as the <br>artistic director for the Yokohama Triennale 2014 among other <br>positions. He continues to be active as an artist both in Japan and <br>overseas.<br>The exhibition comprises four sections: M’s Photo Corridor, Theater of <br>Voices, Square for Dreams and Memories and Hidden Costume <br>Closet. In addition to over 800 of Morimura’s treasured instant <br>photographs taken since 1984, which have rarely been shown in <br>public, the exhibition will feature a specially prepared acoustic space <br>in which the audio from Morimura’s CD Faces, on which he reads his <br>own novel written in 1994, will be recreated as a closet drama. This<br>will be Morimura’s first large-scale solo exhibition in Kyoto since 1998, <br>and the first attempt to reveal the entirety of his private world, which <br>has continued for over thirty-five years.<br>Morimura’s expression, in which the self is deconstructed by taking<br>the place of others to expose the multiple faces of the individual, <br>shares similarities with the “selfie” that has been popularized by the <br>evolution of smartphones and the spread of social media, and yet it <br>also has a decidedly different aspect. In his images, one can discern <br>Morimura’s penetrating gaze at the self, and an overwhelming <br>affirmation of the multiple selves that a person can assume in their <br>lives. By returning to the origin of his own production, this exhibition <br>will present Morimura’s current state as he gropes for the future<br> amidst the effects of the Covid-19 pandemic.',
    subPeriod:'12 March – 5 June, 2022',
    subTime:'10:00〜18:00',
    subVenue :'Higashiyama Cube',
    closedOn :'Mondays (except public holidays)',
    inquiriy:'2022 schedule<br><a href="https://kyotocity-kyocera.museum/en/exhibition/20220429-20230305">https://kyotocity-kyocera.museum/en/exhibition/20220429-20230305</a>'
},
{   //7
    imgSrc :'tera.jpg', 
    imgAlt : 'teraImg',
    name:'[2022 Spring] Collection Room: Picturesque Kyoto',
    period:'April 29 (Fri.) －July 10 (Sun.), 2022',
    venue :' [ Main Building (South Wing)1F ]',
    about:'The Museum has been acquiring Kyoto modern art since its <br>inauguration in 1933, and currently has holdings of over 4,000 <br>artworks comprised of a core of Japanese paintings along with <br>Western style paintings, sculpture, prints, crafts, and calligraphy.<br>The Museum is particularly proud of its highly regarded collection of <br>paintings by Meiji and Showa period Kyoto artists. Introducing <br>paintings with seasonal themes in tandem with the changing seasons, <br>the Museum gives viewers a rich sense of the seasons in Kyoto.<br>Spring: April 29 (Fri.) - July 10 (Sun.), 2022<br>Summer: July 16 (Sat.) - September 25 (Sun.), 2022<br>Fall: September 30 (Fri.) - November 13 (Sun.), 2022<br>Winter: December 4 (Sun.), 2022 - March 5 (Sun.), 2023',
    subPeriod:'Spring: Picturesque Kyoto<br>April 29 (Fri.) - July 10 (Sun.), 2022<br>Summer: Genealogy of Fantasy—Western Print Collection and Western Paintings from Modern Kyoto<br>July 16 (Sat.) - September 25 (Sun.), 2022<br>Fall: Body, Decoration, and Humor<br>October 1 (Sat.) - December 18 (Sun.), 2022<br>Winter: Art in East Asia and Modern Kyoto<br>December 4 (Sun.), 2022 - March 5 (Sun.), 2023',
    subTime:'10:00−18:00 (last admission 17:30)',
    subVenue :'Main Building (South Wing) 1F',
    closedOn :'Mondays (except public holidays)',
    inquiriy:'2022 schedule<br><a href="https://kyotocity-kyocera.museum/en/exhibition/20220429-20230305">https://kyotocity-kyocera.museum/en/exhibition/20220429-20230305</a>'
},
{   //8
    imgSrc :'po.jpg', 
    imgAlt : 'pompeiiImg',
    name:'Exhibition POMPEII',
    period:'2022/4/21-2022/7/3',
    venue :'[ Main Building (North Wing) 1F ]',
    about:'In AD 79, a massive eruption of Mt Vesuvius, near Naples in Italy, <br>caused volcanic matter to engulf the Roman imperial city of Pompeii.<br>Excavation of the buried remains, begun in the eighteenth century, <br>continues today.<br>This exhibition presents various unearthed artifacts, ranging from <br>superb murals, sculpture, and craftwork to daily utensils such as <br>tableware and cookware--enabling us to reimagine the urban society <br>and rich lifestyle of 2,000 years ago. <br>Thanks to the generous cooperation of the National Archaeological <br>Museum of Naples, conserver of a treasure trove of Pompeii artifacts, <br>visitors have a precious opportunity to appreciate “the definitive <br>Pompeii exhibition.”',
    subPeriod:'April 21 - July 3, 2022',
    subTime:'10:00−18:00 (last admission 17:30)',
    subVenue :'Main Buildin (North Wing) 1F',
    closedOn :'Mondays (except public holidays)',
    inquiriy:'Exhibition POMPEII Official website<br><a href="https://pompeii2022.jp/">https://pompeii2022.jp/</a>'
},
{   //9
    imgSrc :'kano.jpg', 
    imgAlt : 'kanoImg',
    name:'Exhibition POMPEII',
    period:'2022/4/21-2022/7/3',
    venue :'[ Main Building (North Wing) 1F ]',
    about:'In AD 79, a massive eruption of Mt Vesuvius, near Naples in Italy, <br>caused volcanic matter to engulf the Roman imperial city of Pompeii.<br>Excavation of the buried remains, begun in the eighteenth century, <br>continues today.<br>This exhibition presents various unearthed artifacts, ranging from <br>superb murals, sculpture, and craftwork to daily utensils such as <br>tableware and cookware--enabling us to reimagine the urban society <br>and rich lifestyle of 2,000 years ago. <br>Thanks to the generous cooperation of the National Archaeological <br>Museum of Naples, conserver of a treasure trove of Pompeii artifacts, <br>visitors have a precious opportunity to appreciate “the definitive <br>Pompeii exhibition.”',
    subPeriod:'April 21 - July 3, 2022',
    subTime:'10:00−18:00 (last admission 17:30)',
    subVenue :'Main Buildin (North Wing) 1F',
    closedOn :'Mondays (except public holidays)',
    inquiriy:'Exhibition POMPEII Official website<br><a href="https://pompeii2022.jp/">https://pompeii2022.jp/</a>'
},
{   //10
    imgSrc :'marvel.jpg', 
    imgAlt : 'marvelImg',
    name:'AVENGERS S.T.A.T.I.O.N.',
    period:'2022/7/8-2022/8/26',
    venue :'[ Higashiyama Cube ]',
    about:'JAPAN, ARE YOU READY TO EXPERIENCE THE MARVEL’S AVENGERS S.T.A.T.I.O.N. <br>EXHIBITION?<br>MARVEL AVENGERS S.T.A.T.I.O.N. made its debut in New York in July 2014, and has showcased the Avengers worldwide in 24 cities (12 <br>countries) including Paris, London and Las Vegas. It is the show where guests will experience the Marvel Cinematic Universe in a journey through <br>this high-energized facility. Here they can explore their favorite characters, and villains, discovering intelligence, technology and cutting-edge <br>science of the Avengers and experience interactive challenges and simulations.<br>Official Website for AVENGERS S.T.A.T.I.O.N. (Tokyo and Kyoto) https://avengersstation.jp/ ',
    subPeriod:'July 8 - August 26, 2022',
    subTime:'10:00〜18:00 Last Admission: 17:30',
    subVenue :'Higashiyama Cube',
    closedOn :'Mondays, except July 18',
    inquiriy:'Official Website for AVENGERS S.T.A.T.I.O.N. (Tokyo and Kyoto)<br><a href="https://avengersstation.jp/">https://avengersstation.jp/</a><br>Hello Dial 050-5542-8600 (within Japan)<br>9:00-20:00;daily'
},
{   //11
    imgSrc :'kira.jpg',
    imgAlt :'kiraImg',
    name:'Ornate Meiji Period Art: Shining Kyoto Artists of the Imperial Court',
    period:'2022/7/23-2022/9/19',
    venue :' [ Main Buildin (South Wing) 1F ]',
    about:'The Imperial Court artist system was established in 1890 by the <br>Ministry of the Imperial Household to honor and protect outstanding <br>artists and craftsmen. Considered the front-runners of the art world, <br>only a handful of artists were selected.<br>In addition to encouraging art, the purpose behind the system’s<br>establishment was to help painters and craftspeople facing hardship <br>after losing the protection of the shogunate and other fiefdoms <br>following the Meiji Restoration, while also preserving their exceptional <br>skills. The Imperial Court artists were bestowed the highest honor <br>and authority in the art world of their time, and many artists with ties to <br>Kyoto were selected to join the system throughout its duration until <br>1944. This exhibition introduces nineteen Imperial Court artists with <br>ties to Kyoto, focusing on the Meiji Period when the system was first <br>established. Visitors are invited to experience the skill and beauty of <br>Meiji Period Kyoto through masterpieces that have been celebrated as <br>the greatest of their kind.',
    subPeriod:'July 23 (Sat.) - September 19 (Mon. national holiday)<br>Part 1: July 23 (Sat.) - August 21 (Sun.)<br>Part 2: August 23 (Tue.) - September 19 (Mon. national holiday)',
    subTime:'10:00〜18:00 Last Admission: 17:30',
    subVenue:'Main Building (South Wing) 1F',
    closedOn:'Mondays, except public holidays',
    inquiriy:'',
},
{   //12
    imgSrc :'nitten.jpg',
    imgAlt :'nittenImg',
    name:'The Nitten-Kyoto Exhibition',
    period:'2020/12/19-2021/1/15',
    venue :' [ Main Building（North Wing）1F | Main Building（North Wing）2F<br>Main Building（South Wing）2F ] ',
    about:'The 7th Reorganized New Nitten in Kyoto, the Kyoto showing of the<br> national tour of Japan’s largest public exhibition, will feature artworks<br>  related to Kyoto and Shiga as well as the 5 traditional Nitten<br>  categories （nihonga, Western painting, sculpture, crafts, and<br>  calligraphy）.',
    subPeriod:'Dec. 19（Sat）, 2020 – Jan. 15（Fri）, 2021',
    subTime:'10:00〜18:00（Last Admission: 17:30）',
    subVenue:'Main Building（North Wing）1F | Main Building（North Wing）2F |<br> Main Building（South Wing）2F',
    closedOn:'Mondays, except public holidays, and Year-end／New Year holidays.',
    inquiriy:'',
},
{   //13
    imgSrc :'botero.jpg',
    imgAlt :'boteroImg',
    name:'BOTERO MAGIC IN FULL FORM',
    period:'2022/10/8-2022/12/11',
    venue :' [ Main Building (North Wing) 1F ]',
    about:'This exhibition celebrates the 90th anniversary of the<br> birth of the Colombian artist Fernando Botero, and under the supervision of<br> Botero himself, presents 70 oil paintings, watercolors and drawings,<br> from his valuable early works to his recent works. This is the first time<br> in 26 years that a large-scale exhibition of paintings has been held<br> in Japan. From works depicting the daily lives and religions of Latin<br> American people, and the circus, to those based on the classical<br> masterpieces that made his name famous, Botero’s works have<br> captivated viewers, in exhibitions that have been held all around the<br> world.',
    subPeriod:'October 8 (Sat.)- December 11 (Sun.), 2022',
    subTime:'10:00~18:00',
    subVenue:'Main Building (North Wing) 1F',
    closedOn:'Mondays (except October 10)',
    inquiriy:'Official Website<br><a href="https://www.ytv.co.jp/botero2022/">https://www.ytv.co.jp/botero2022/</a><br>KYODO information 0570-200-888 11:00-18:00; Monday to Saturday',
},
{   //14
    imgSrc :'hicosaka.jpg',
    imgAlt :'hicosakaImg',
    name:'Hicosaka Toshiaki: Sand Story',
    period:'2022/5/31-2022/9/25',
    venue :' [ The Triangle ]',
    about:'Hicosaka Toshiaki is an artist who focuses on creating ways to share<br> a space and time with people or objects. By collaborating with others<br> and gradually building “places,” he attempts to carefully ascertain the<br> existence of things and people decisively different from himself.<br>The process of conceiving this exhibition led Hicosaka to the sand<br> that lies under our feet. During the initial preparation, he would go on<br> walks with his collaborators (who he calls his “companions”), touch,<br> pick up, and examine the sand, and then bring back various<br> sensations and images. Sand is an everyday substance but also<br> something both literally and figuratively shifting and difficult to grasp.<br> The exhibition has amassed countless numbers of little “sand stories”<br> dealing with this elusive substance.<br>The exhibition gallery features sandboxes for visitors to touch and<br> examine sand with their own hands, and even walk on it. Other<br> exhibits include videos and small works about sand, opening up the<br> gallery as a place for people to gather.<br>Each visitor to the exhibition will surely take home their own sand<br> story.<br>The Triangle<br>The Triangle is a space newly created for the reopening of the Kyoto<br> City KYOCERA Museum of Art. It aims to nurture emerging artists,<br> especially those associated with Kyoto, and to provide opportunities<br> for museum visitors to experience contemporary art. In order to<br> connect the artist, museum, and viewer in a triangle and deepen<br> those connections, the space hosts an eponymous series of special<br> exhibitions and presents new artistic expressions from Kyoto.<br>Graphic Design<br>The Triangle’s graphic design in 2022 is by Nishimura Yuichi<br> (rimishuna). As this series of exhibitions that supports emerging<br> artists with connections to Kyoto enters its third year, the museum<br> searched for a fresh style by a designer similarly with links to the city<br> where it is located. In Nishimura’s design, text is laid over a triangle of<br> rough, hand-drawn lines, forming an image of the works in the<br> exhibition.',
    subPeriod:'May 31 (Tue.) - September 25 (Sun.), 2022',
    subTime:'10:00〜18:00 Last Admission: 17:30',
    subVenue:'The Triangle',
    closedOn:'Mondays (except public holidays)',
    inquiriy:'Organizer: City of Kyoto<br>Cooperation: YAMAKAWA SANGYO CO.,LTD., Konishi Yugo (Tama Plant)<br>Production Cooperation: Childrens Academy of Art and Education',
},
{   //15
    imgSrc :'kawato.jpg',
    imgAlt :'kawatoImg',
    name:'Kawato Aya: Diagonal Dimension',
    period:'2022/2/8-2022/5/15',
    venue :'[ The Triangle ]',
    about:'Kawato Aya creates unique grid forms on a theme of control and lack<br>thereof, that is, deviation. The term “deviation” as used here has<br>origins in the textile dyeing studied by the artist at university,<br>refers to the distortions that unavoidably occur when underta<br>delicate handwork. This in turn is linked to the neuroscience <br>forms another of Kawatoʼs interests, in particular the optical illus<br>that arise from sensate “deviations” in the form of discrepan<br>between vision and cognition. Just as one might spin thread<br>weave cloth, Kawato meticulously overlays countless painted col<br>lines on one another. The resulting grids with their distortions<br>imperfections have an unmistakably handcrafted warmth that <br>them apart from the cold, sterile-looking Op Art (abstract paint<br>and sculptures triggering powerful optical illusions) of post<br>Ame<br>This exhibition will see Kawato unfold through the entire gallery s<br>a grid creation with the contrasting textures of hand drawing<br>digital print. Resonating with the three-sided space of The Triangl<br>grid pattern formed by vertical and diagonal lines will surround<br>spectator, exploring in its endless, oscillating weave an unk<br>dimension beyond our cognition or control, that shifts tantalizi<br>according to the viewing angle and distance.<br>The Triangle<br>The Triangle is a space newly created for the reopening of the Kyoto <br>City KYOCERA Museum of Art. It aims to nurture emerging artists, <br>especially those associated with Kyoto, and to provide opportunities <br>for museum visitors to experience contemporary art. In order to <br>connect the artist, museum, and viewer in a triangle and deepen <br>those connections, the space hosts an eponymous series of special <br>exhibitions and presents new artistic expression from Kyoto.',
    subPeriod:'February 8 (Tue) – May 15 (Sun), 2022',
    subTime:'10:00-18:00',
    subVenue:'The Triangle',
    closedOn:'Mondays, except 2 May and public holidays.',
    inquiriy:'',
},
{   //16
    imgSrc :'sun.jpg',
    imgAlt :'sunImg',
    name:'Kano Shunsuke: Gaps in the Sandwich',
    period:'2021/10/26-2022/1/23',
    venue :' [ The Triangle ]',
    about:'Kano Shunsuke is a Kyoto-based artist who works primarily with <br>photography. His practice involves taking photograph after <br>photograph, building them up into a single, complexly layered print <br>in an endeavor to offer glimpses of images of another world within <br>everyday things and landscapes.<br>The gallery on the first basement floor features Kano’s latest entry <br>in Pink Shadow, the series central to his recent practice. By adding a <br>transparent sheet with a dot pattern to the back of a photograph and <br>lighting this from behind to rephotograph it, he expresses the <br>complexity of positional relationships. The result evokes in viewers a <br>sense of uncertainty over their response to what they are seeing. The <br>ground-floor glass wall showcases a large installation with the most <br>recent in Kano’s compression training drawing and collage series, <br>created like daily sketches and here blown up and printed on fabric. <br>Explore the mystery of “seeing” that accompanies novel subversions <br>of perception.<br>About “The Triangle”<br>“The Triangle” is a space that is newly created on the <br>occasion of the renewal opening of the Kyoto City KYOCERA Museum of Art. Our <br>aim is for it to become a venue to nurture emerging artists, centered on <br>artists associated with Kyoto, and to provide an opportunity for <br>museum visitors to experience contemporary art. In order to connect <br>the “artist, museum and viewer” in a triangle and deepen their <br>connection, we will use this space to host a series of special <br>exhibitions bearing the name “The Triangle” as we set out to present <br>new artistic creations from Kyoto.',
    subPeriod:'Oct. 26, 2021 - Jan. 23, 2022',
    subTime:'10:00〜18:00',
    subVenue:'The Triangle',
    closedOn:'Mondays, New Year holidays (Dec.28 - Jan.2)<br>* except public holidays.',
    inquiriy:'',
},
{   //17
    imgSrc :'coll.jpg',
    imgAlt :'collImg',
    name:'[2021 Schedule] Collection Room',
    period:'2021/3/20-2022/3/13',
    venue :' [ Main Building (South Wing) 1F ]',
    about:'The Museum has been acquiring Kyoto modern art since its <br>inauguration in 1933, and currently has holdings of over 3,800 <br>artworks comprised of a core of Japanese paintings along with<br>Western style paintings, sculpture, prints, crafts, and calligraphy.<br>The Museum is particularly proud of its highly regarded collection of <br>paintings by Meiji and Showa period Kyoto artists. Introducing <br>paintings with seasonal themes in tandem with the changing seasons, <br>the Museum gives viewers a rich sense of the seasons in Kyoto.<br>Spring: Mar. 20 (Sat, public holiday) – Jun. 20 (Sun), 2021<br>Summer: Jun. 26 (Sat.) - Sep. 26 (Sun) , 2021<br>Fall: Oct. 2 (Sat.) - Dec. 5 (Sun.), 2021<br>Winter: Dec. 11 (Sat.), 2021 - Mar. 26 (Sat.), 2022',
    subPeriod:'Spring: Mar. 20 (Sat, public holiday) - Jun. 20 (Sun), 2021<br>Summer: Jun. 26 (Sat.) - Sep. 26 (Sun) , 2021<br>Fall: Oct. 2 (Sat.) - Dec. 5 (Sun.), 2021<br>Winter: Dec. 11 (Sat.), 2021 - Mar. 26 (Sat.), 2022',
    subTime:'10:00-18:00',
    subVenue:'Main Building（South Wing）1F',
    closedOn:'Mondays (except public holidays)',
    inquiriy:'',
},
{   //18
    imgSrc :'kodai.jpg',
    imgAlt :'kodaiImg',
    name:'Terracotta Warriors and Ancient China Heritage from the Qin and Han<br> Dynasty',
    period:'2022/3/25-2022/5/22',
    venue :' [ Main Building (North Wing) 2F ]',
    about:'In 1974, a farmer digging a well in a field in China came upon the <br>terracotta warriors by chance, and the world was amazed by this <br>discovery of a huge number of life-sized pottery soldiers and horses <br>made over 2000 years ago. The number is estimated to be about <br>8,000 pieces, and research still continues to this day.<br>The year 2022 marks 50 years from the normalization of diplomatic <br>relations between Japan and China. To commemorate this occasion <br>and place focus on the history of ancient China, the terracotta <br>warriors who have been protecting the emperor since his death, will <br>be on display in Japan<br>In 221 B.C., Emperor Qin Shihuang established the first unified <br>empire in Chinese history. The Han Empire founded later by Liu Bang <br>was one of the golden ages of ancient China. This exhibition <br>dynamically displays approximately 200 pieces of artifacts excavated <br>in Guanzhong (present-day Shaanxi Province), the central region of <br>the Qin and Han empires, including first-class cultural artifacts (a <br>unique Chinese classification that refers to the finest and most <br>valuable artifacts), which are being displayed for the first time in <br>Japan. With the actual artifacts, visitors can observe the historical <br>wonder of how the tiny terracotta warriors of the Warring States <br>period became life-size terracotta warriors at the Mausoleum of the <br>First Emperor, and then into smaller terracotta warriors at the <br>Mausoleum of the Han Dynasty Emperors. The exhibition also focuses <br>on the similarities between the Mausoleums of the First Emperor and <br>Han Emperors and the pyramids of Egypt, and explores the mysteries <br>of ancient mausoleums in the East and West through satellite images. <br>This is a fascinating exhibition with fresh new perspectives.<br>Xian City, Shaanxi Province in China, with the Mausoleums of the <br>First Qin Emperor, is a sister city of the City of Kyoto.',
    subPeriod:'March 25 - May 22, 2022',
    subTime:'10:00〜18:00 (Last Admission: 17:30)',
    subVenue:'Main Building (North Wing) 2F',
    closedOn:'Mondays, except 2 May and public holidays.',
    inquiriy:'"Terracotta Warriors and Ancient China Heritage from the Qin and Han<br> Dynasty" website<br><a href="https://heibayou2022-23.jp/">https://heibayou2022-23.jp/</a>',
},
{   //19
    imgSrc :'patin.jpg',
    imgAlt :'patinImg',
    name:'3rd Print Art Triennale in Kyoto 2022',
    period:'2022/4/12-2022/5/8',
    venue :'[ Main Building (South Wing) 2F ]',
    about:'Japans extraordinary culture of printmaking is widely known : the <br>global influence of ukiyo-e prints, the bold achievements of the <br>sosaku hanga (creative prints) movement, the international success of <br>Japanese printmakers after World War II.<br>The International Biennial Exhibition of Prints in Tokyo was launched <br>in 1957, and in the context of the worldwide flourishing of printmaking, <br>society as a whole came to recognize prints as a contemporary art <br>medium. In the 1960s and 1970s, which have been called the golden <br>age of contemporary printmaking, prints gained status as a full-<br>fledged mode of expression and attained an unassailable position in <br>Japanese culture. Since the 1980s Japanese printmaking has grown <br>ever more original and sophisticated, maturing in such a way that <br>Japan can truly be called a global leader in prints in a way no other <br>country or region can. The 1st PATinKyoto Print Art Triennale in Kyoto <br>was organized with the goals of showcasing the richness of <br>printmaking in the present continuous tense, and of establishing <br>critical perspectives for sufficient assessment of the works. It also <br>monstrated that the enterprising spirit of the art of printmaking is <br>particularly pronounced among printmakers in Kyoto. And this project, <br>situated in the ancient capital of Kyoto, has gained support from a <br>wide range of companies and private citizens, and has gained high <br>acclaim from the mass media and various other organizations.<br>Following the 1st and 2nd editions, we have organized the 3rd <br>PATinKyoto Print Art Triennale 2022, aiming to introduce fresh <br>innovation to the culture of Kyoto and transmit it to the world. We are <br>preserving the selection format of the previous two editions: while <br>most art competitions invite entries from the public, the Triennale is <br>unique in that entries are recommended by commissioners who have <br>a keen artistic sense and are well informed about printmaking. Also,<br>we offer a spacious venue in which artists can exhibit a series of <br>works or a large installation-style work. Moving forward, we intend to <br>further develop this unprecedented endeavor at the newly renovated <br>Kyoto City KYOCERA Museum of Art.<br>Looking beyond the conventional framework of printmaking, a wide <br>variety of contemporary prints including photographs, computer <br>graphics, and even 3D works will be exhibited throughout the <br>museum. The goal is to make a major impact on the general public, <br>the art world, and the mass media with an event that symbolizes a <br>progressive, forward-looking Kyoto.<br>Focusing on the ever-evolving diversity of prints, we will present a <br>contemporary printmaking exhibition in a new framework so as to <br>encourage the further maturation of the medium and transmit the <br>results to the world. Our objective is to showcase the abundant variety <br>of prints, as traditional Japanese culture and as a contemporary art <br>form, and disseminate it from Kyoto, a city of art and culture, to the <br>world.',
    subPeriod:'April 12 (Tue.) − May 8 (Sun.), 2022',
    subTime:'10:00～18:00 (last admission 17:30)',
    subVenue:'Main Building（South Wing）2F',
    closedOn:'Mondays, except 2 May and public holidays.',
    inquiriy:'Official website <a herf="https://patinkyoto.info">https://patinkyoto.info</a>',
},
{   //20
    imgSrc :'penn.jpg',
    imgAlt :'pennImg',
    name:'KYOTOGRAPHIE 2022',
    period:'<br>Irving Penn<br>Irving Penn: Works 1939–2007. Masterpieces from the MEP Collection<br>Presented by DIOR<br>From the collection of MEP, Paris (Maison Européenne de la Photographie) in collaboration with The<br> Irving Penn Foundation2022/4/9-2022/5/8',
    venue :' [ Annex ]',
    about:'The Maison Européenne de la Photographie in Paris has one of the <br>most significant and complete European collections of the works of <br>the American Photographer Irving Penn (1917-2009). This unique <br>ensemble is primarily the result of the longstanding and close <br>relationship between MEP and the artist himself, during his lifetime, <br>and more recently a close and precious collaboration with The Irving <br>Penn Foundation, led by his son, Tom Penn. Today the MEP holds <br>over 100 vintage works, which not only span the entirely of Penn’s <br>working life, but includes some of his most celebrated and iconic <br>images. This presentation of 80 works, specially selected for <br>KYOTOGRAPHIE by MEP, offers its audience in Japan an <br>unparalleled insight, not only into the richness and diversity of Penn’s <br>images but also his incredible skill as a print-maker. Penn’s <br>photographs, in silver gelatin, platinum-palladium, and colour <br>processes, are among the most highly cherished in the history of <br>photography, effortlessly bringing to life, and in the highest possible <br>quality, the whole range of photographic genres from still life and <br>andscape, to portraiture and fashion. It is with the latter in mind that <br>KYOTOGRAPHIE and MEP have worked closely with our colleagues <br>at Maison Dior in Japan and France to bring this priceless body of <br>work to a new audience for the first time.<br>From his earliest documentary work in late 1930s America, and during <br>the Second World War, to his poignant final still life pictures, Irving <br>Penn strived always to produce photographs of the very highest <br>quality. As such he is perhaps without equal in being celebrated as <br>much for his pictorial ingenuity in commercial and commissioned work <br>as for his expressive artistry. There are no distinctions in quality in <br>Penn’s oeuvre between the absolute attention given to an apparently <br>simple still life, even a crushed cigarette or piece of gum, and the <br>beauty and sophistication of his fashion pictures or celebrity portraits. <br>Each subject finds its proper place, and achieves its artistic statuss <br>through a complex and life-learned process of looking, thinking, <br>composition and perfect technical reproduction.<br>[Quotation from the introduction text by Simon Baker, Director of <br>Maison Européenne de la Photographie]',
    subPeriod:'April 9 (Sat) − May 8 (Sun), 2022',
    subTime:'10:00 - 17:30 (Last admission 17:00)',
    subVenue:'Annex',
    closedOn:'Mondays, except 2 May and public holidays.',
    inquiriy:'',
},
{   //21
    imgSrc :'hana.jpg',
    imgAlt :'hanaImg',
    name:'[2021 Winter] Collection Room',
    period:'2021/12/11-2022/3/26',
    venue :' [ Main Building（South Wing）1F ]',
    about:'The Museum has been acquiring Kyoto modern art since its <br>inauguration in 1933, and currently has holdings of over 3,800 <br>artworks comprised of a core of Japanese paintings along with <br>Western style paintings, sculpture, prints, crafts, and calligraphy.<br>The Museum is particularly proud of its highly regarded collection of <br>paintings by Meiji and Showa period Kyoto artists. Introducing <br>paintings with seasonal themes in tandem with the changing seasons, <br>the Museum gives viewers a rich sense of the seasons in Kyoto.<br>A feeling of summer in the early Showa period can be gleaned from <br>works such as Kitano Tsunetomi Sisters of a Merchant Family,<br>depicting a hot summer evening conversation in a garden, and Showa <br>period oil painter Nakamura Ken-ichi’s The Seto Inland Sea of Japan.<br>To give a feeling of activities from midwinter and early spring, this <br>exhibition features works such as female painter Kitazawa Eigetsu’s <br>Bright Kimono, depicting girls preparing their spring kimonos, and<br>Nakamura Hosei’s humorous winter peony brocade tapestry of plants <br>wrapped in protective covering for the winter.',
    subPeriod:'Dec. 11 (Sat.), 2021 – Mar. 26 (Sat.), 2022',
    subTime:'10:00 - 17:30',
    subVenue:'Main Building（South Wing）1F',
    closedOn:'Mondays, except public holidays',
    inquiriy:'',
},

];//datas


$('.imgWrap').children().click(function(e){
   
    let i = $(this).index();
    let KEY = 'subpage';
    let contents = JSON.stringify(datas[i]);
    localStorage.setItem(KEY,contents);
    


});



});